### ISSUE TITLE
Pebblo Safe Retriever details in Local UI

### ISSUE THREAD

**Issue by shreyas-damle** [daxa-ai/pebblo#342]
We would like to have Safe Retriever Details on the local UI. Here two separate tabs would be shown for loader type and retrieval type applications.
This would include below details on Safe Retrieval App listing page:
* [ ] Active Users (with mouse over showing actual "Top" users - cut off at N user-ids, N = 3)
* [ ] Retrieve Documents (with mouse over showing "Top" documents retrieved - cut off at N user-ids, N = 3)
* [ ] Retrievals (i.e. prompt count, cumulative)
* [ ] VectorDB (with mouse over showing first N vector db names, N=3)
* [ ] Owner(app owner)

**Comment by srics** [comment]
Delivered in v0.1.15. Closing.
